name = "TFL"
version = "0.1.0"
description = "A formalization of the Crosslink 2 hybrid consensus protocol."
keywords = ["math", "cryptography", "proof-of-work", "consensus"]
homepage = "https://github.com/Electric-Coin-Company/tfl-book"
license = "MIT"
defaultTargets = ["TFL"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "TFL"
